FROM golang:alpine AS builder
LABEL stage=netspeed-intermediate
RUN apk -U --no-cache add git make

WORKDIR /go/src/github.com/alexey-zayats/netspeed
COPY ../.. .

RUN make binary

FROM alpine:latest AS runner

WORKDIR /app

COPY --from=builder /go/src/github.com/alexey-zayats/netspeed/bin/netspeed /app/netspeed

RUN apk -U --no-cache add bash ca-certificates \
    && chmod +x /app/netspeed

ENTRYPOINT ["/app/netspeed"]
